### ISSUE TITLE
New Cards Design

### ISSUE THREAD

**Issue by Pranshu321** [Lumos-metaverse/Voting-platform-on-Polygon#10]
I propose a more intuitive and pleasant card design for your platform. The new card design will enhance the user experience by providing a better visual hierarchy and improving the overall look and feel. The design will be more user-friendly and easy to navigate, ensuring efficiency. With this update, our platform will be more modern, attractive, and engaging for our users. Let's make dapp more visually appealing and user-friendly!

**Comment by Pranshu321** [comment]
Hello @KanishkKhurana  , I want to work on this issue. Can you assign me this issue.

**Comment by KanishkKhurana** [comment]
sounds really good @Pranshu321 , lets proceed by making a design using figma (or any other software you like) and upon finalising that you can take over coding it out as well!

**Comment by Pranshu321** [comment]
@KanishkKhurana Actually I don't have much idea about Figma and any other designing platform, and I am not so good at design but, I tried designing a card and attaching screenshots of it please give your reviews and suggestions.

![image](https://user-images.githubusercontent.com/86917304/222897745-6375340c-2fcc-457b-9615-8396108f43c4.png)

**Comment by KanishkKhurana** [comment]
Hey @Pranshu321 , while i think you've  done a good job, lets add more interactivity in this card on hover. 
this change can be simply done by changing the flexbox properties, so lets push for something more fun !

**Comment by Pranshu321** [comment]
Okay @KanishkKhurana Sir , I will add some effects.

**Comment by Pranshu321** [comment]
@KanishkKhurana Sorry for the delay as my exams are going I am unable to proceed and but now I give my full dedication as you added some animation I have added the animation you can see in the video given below and approved so that I can create the pull request.

## Demo 

https://user-images.githubusercontent.com/86917304/226606364-fe29f4c0-7e98-40ad-8087-3bc9c058ae42.mp4

**Comment by KanishkKhurana** [comment]
Looks Lovely! Great Job buddy, please raise a PR !
