### ISSUE TITLE
Adding Lumos's Favicon

### ISSUE THREAD

**Issue by AKHIL-GIREESH** [Lumos-metaverse/Voting-platform-on-Polygon#15]
Replacing the default React's Favicon by that of Lumos's logo.
Hi, I'd love to work on this issue.
Thank you!

**Comment by KanishkKhurana** [comment]
Sure ! Go Ahead!

**Comment by AKHIL-GIREESH** [comment]
Thank you for assigning it to me!
Could you share the img of the Organisation's logo? [ To eliminate Copy-write issues if any ]
I'll set it as the Favicon right away 🙂

**Comment by KanishkKhurana** [comment]
![favicon](https://user-images.githubusercontent.com/74613246/227042207-f9334db9-0075-4bfd-8bab-329814e1f64a.png)

**Comment by KanishkKhurana** [comment]
here you go @AKHIL-GIREESH
