### ISSUE TITLE
Like to update the styling of the project to Enhance the user experience.

### ISSUE THREAD

**Issue by BaibhavTiwari** [Lumos-metaverse/Voting-platform-on-Polygon#18]
Tried to update the Styling of the project !!
>here's the results ![image](https://user-images.githubusercontent.com/75496387/225378566-9aa8c655-1fbc-4695-8deb-457a12b61136.png)

**Comment by BaibhavTiwari** [comment]
@KanishkKhurana, will like to work on enhancing the styling of the project.
can you please assign me this.

**Comment by KanishkKhurana** [comment]
Hey @baibhav-tiwari , We are soon going to integrate a more interactive design in this week with animations. while your design is also good, i believe this can be merged into the design that we will soon merge into main.

I will notify you once that happens and you can make suitable edits then.

**Comment by BaibhavTiwari** [comment]
Thanks, waiting for the new design to be merged!!
