### ISSUE TITLE
Need more frame work to vote 

### ISSUE THREAD

**Issue by Hardik29** [Lumos-metaverse/Voting-platform-on-Polygon#4]
![image](https://user-images.githubusercontent.com/28181759/220917323-468cb054-f1b9-414d-95ec-8dd0a6ad3893.png)

**Comment by dhruvdabhi101** [comment]
I would like contribute to this issue. Can you please assign this issue to me ?

**Comment by KanishkKhurana** [comment]
absolutely @dhruvdabhi101 .
Please ensure that you are forking the project and raising the PR once you are done.
