### ISSUE TITLE
Add support for multiple wallets

### ISSUE THREAD

**Issue by KanishkKhurana** [Lumos-metaverse/Voting-platform-on-Polygon#7]

**Comment by abhinow01** [comment]
hey @KanishkKhurana , would like to start with this issue , can you elaborate on the issue a bit more , my understanding of the issue is , we have to enable the app in a way that it can interact with different  wallets

**Comment by tab21** [comment]
hi @KanishkKhurana I would like to work on this issue, can this be assigned to me please
I was thinking of using web3modal to be able to connect multiple wallets.
